# Generated by Django 2.2.4 on 2020-01-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=85, null=True)),
                ('link', models.CharField(max_length=250, null=True)),
                ('descricao', models.TextField(null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='home/')),
            ],
        ),
        migrations.CreateModel(
            name='AppMonitoramento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=85, null=True)),
                ('link', models.CharField(max_length=250, null=True)),
                ('descricao', models.TextField(null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='monitoramento/')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=85, null=True)),
                ('link', models.CharField(max_length=250, null=True)),
                ('descricao', models.TextField(null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='feed/')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=85, null=True)),
                ('link', models.CharField(max_length=250, null=True)),
                ('descricao', models.TextField(null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em:')),
                ('upload_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Upload em:')),
                ('categoria', models.CharField(choices=[('Alertas de Indícios de Queimadas e Desmatamento', 'Alertas de Indícios de Queimadas e Desmatamento'), ('Biblioteca Brasília Ambiental', 'Biblioteca Brasília Ambiental'), ('Catálogo de Metadados', 'Catálogo de Metadados'), ('Dados Abertos', 'Dados Abertos'), ('ETEPs', 'ETEPs'), ('Eu Amo Cerrado', 'Eu Amo Cerrado'), ('Geoinformação', 'Geoinformação'), ('Geoserviço', 'Geoserviço'), ('Monitoramento Ambiental', 'Monitoramento Ambiental'), ('Qualificação dos Alertas de Queimadas e Desmatamento', 'Qualificação dos Alertas de Queimadas e Desmatamento'), ('Urutau', 'Urutau')], max_length=100)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-criado_em'],
            },
        ),
    ]
